### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gy741** [shuque/resolve#1]
Hello,

I get error.

```
root$ resolve.py
Traceback (most recent call last):
  File "/usr/local/bin/resolve.py", line 4, in <module>
    __import__('pkg_resources').run_script('resolve==0.31', 'resolve.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/resolve-0.31-py3.6.egg/EGG-INFO/scripts/resolve.py", line 10, in <module>
  File "/usr/local/lib/python3.6/dist-packages/resolve-0.31-py3.6.egg/reslib/main.py", line 16, in <module>
  File "/usr/local/lib/python3.6/dist-packages/resolve-0.31-py3.6.egg/reslib/query.py", line 11, in <module>
  File "/usr/local/lib/python3.6/dist-packages/resolve-0.31-py3.6.egg/reslib/dnssec.py", line 15, in <module>
ImportError: cannot import name 'ECC'

```

**Comment by shuque** [comment]
The ECC module comes from the pycryptodome package. Do you have pycryptodome installed?

https://www.pycryptodome.org/en/latest/

pip install pycryptodome
